function(ntt_assert_only_one_is_on)
    set(has_on_option OFF)
    set(latest_on_option "")
    foreach(option IN ITEMS ${ARGN})
        if (${option} STREQUAL "ON")
            if (has_on_option STREQUAL "OFF")
                set(has_on_option ON)
                set(latest_on_option ${option})
            else()
                message(FATAL_ERROR "Only one of the following options can be ON: ${ARGN}. Both ${option} and ${latest_on_option} are ON.")
            endif()
        endif()
    endforeach()

    if (has_on_option STREQUAL "OFF")
        message(FATAL_ERROR "One and only one of the following options must be ON: ${ARGN}")
    endif()

endfunction()

function(ntt_assert_at_least_one_is_on)
    set(has_on_option OFF)
    foreach(option IN ITEMS ${ARGN})
        if (${option} STREQUAL "ON")
            if (has_on_option STREQUAL "OFF")
                set(has_on_option ON)
            endif()
        endif()
    endforeach()

    if (has_on_option STREQUAL "OFF")
        message(FATAL_ERROR "At least one of the following options must be ON: ${ARGN}")
    endif()
endfunction()

function(ntt_assert_max_one_is_on)
    set(has_on_option OFF)
    set(latest_on_option "")
    foreach(option IN ITEMS ${ARGN})
        if (${option} STREQUAL "ON")
            if (has_on_option STREQUAL "OFF")
                set(has_on_option ON)
                set(latest_on_option ${option})
            else()
                message(FATAL_ERROR "Only one (or none) of the following options can be ON: ${ARGN}. Both ${option} and ${latest_on_option} are ON.")
            endif()
        endif()
    endforeach()
endfunction()