macro(ntt_config)
    set(NTT_OPTIONS)
    set(NTT_LINK_FLAGS)

    if (MSVC)
        set_property(GLOBAL PROPERTY USE_FOLDERS ON)
    endif()

    option(CMAKE_BUILD_TYPE "Build type" Debug)
    ntt_option(NTT_ENABLE_ASSERTION ON)

    if (CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(NTT_DEBUG ON)
        list(APPEND NTT_OPTIONS NTT_DEBUG)
    elseif (CMAKE_BUILD_TYPE STREQUAL "Release")
        set(NTT_RELEASE ON)
        list(APPEND NTT_OPTIONS NTT_RELEASE)
    else()
        message(FATAL_ERROR "Unsupported build type: ${CMAKE_BUILD_TYPE}")
    endif()

    ntt_platform_detect()
endmacro()

macro(ntt_platform_detect)
    if (EMSCRIPTEN)
        set(NTT_PLATFORM_WEB ON)
        list(APPEND NTT_OPTIONS NTT_PLATFORM_WEB)
    elseif (WIN32)
        set(NTT_PLATFORM_WINDOWS ON)
        list(APPEND NTT_OPTIONS NTT_PLATFORM_WINDOWS)
    elseif (APPLE)
        message(FATAL_ERROR "Apple platform is not supported yet")
    elseif (UNIX)
        set(NTT_PLATFORM_UNIX ON)
        list(APPEND NTT_OPTIONS NTT_PLATFORM_UNIX)
    else()
        message(FATAL_ERROR "Unsupported platform")
    endif()
endmacro()

function(ntt_add_options target)
    message(STATUS "OPTIONS:")
    foreach(option IN LISTS NTT_OPTIONS)
        if (${${option}} STREQUAL "ON")
            target_compile_definitions(${target} PUBLIC ${option}=1)
            message("        ${option}=1")
        elseif (${${option}} STREQUAL "OFF")
            target_compile_definitions(${target} PUBLIC ${option}=0)
            message("        ${option}=0")
        else()
            target_compile_definitions(${target} PUBLIC ${option}=${${option}})
            message("        ${option}=${${option}}")
        endif()
    endforeach()
endfunction()

macro(ntt_option option default_value)
    option(${option} "Option ${option}" ${default_value})
    list(APPEND NTT_OPTIONS ${option})
endmacro()